---

- name: Install common desktop packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - ack-grep
    - aptitude
    - bash-completion
    - bzip2
    - curl
    - git
    - git-core
    - git-flow
    - git-email
    - git-extras
    - git-svn
    - gzip
    - htop
    - pwgen
    - tar
    - terminator
    - tig
    - ubuntu-restricted-extras # MP3, Microsoft fonts, Flash plugin, LAME and DVD playback
    - unetbootin # create bootable USB drives
    - unzip
    - vim
    - vlc
    - wget
    - zsh

- name: Linux | Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Linux | Upgrade
  apt: upgrade=dist

- name: Install common desktop packages if Ubuntu 18.04
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - fonts-hack-ttf
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: Block Ubuntu product search in system host file
  lineinfile: dest=/etc/hosts regexp="^127\.0\.0\.1   productsearch.ubuntu.com$" line="127.0.0.1   productsearch.ubuntu.com" state=present

- name: Ensure that lightdm configuration directory exists
  file: path=/etc/lightdm/lightdm.conf.d state=directory

- name: Disable guest session in lightdm
  copy: src="50-no-guest.conf" dest="/etc/lightdm/lightdm.conf.d/50-no-guest.conf" force=no
