---

# Install custom vim
- name: VIM | Clone vim config
  sudo: false
  git: repo=git@github.com:volcomism/vimrc.git
       dest={{ local_home }}/.vim-config
       update=yes
       accept_hostkey=yes
       recursive=yes

- name: VIM | Created symlink (vimrc)
  sudo: false
  file: src={{ local_home }}/.vim-config/vimrc dest={{ local_home }}/.vimrc owner={{ user }} group={{ user }} state=link

- name: VIM | Created symlink (.vim/)
  sudo: false
  file: src={{ local_home }}/.vim-config/vim dest={{ local_home }}/.vim owner={{ user }} group={{ user }} state=link
