---

- name: Add alfred key
  apt_key:
    url: https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.04/Release.key
    state: present

- apt_repository:
  repo: deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04 amd64
  state: present

- name: Install Albert
  apt: name=albert state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
